# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'password-manager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for password-manager
  
  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  # Credentials
  pod 'PwGen'
  pod 'RNCryptor'
  pod 'SwiftyHash'
  
  # Pods for SCLAlertView
  pod 'SCLAlertView'
  
  # Overlays Spinner
  pod 'SwiftOverlays', '~> 5.0.1'
end
